/**
 * pages/config.js — Config page.
 */
import { ui, clipboard, notify, pagination, tabs } from '../lib/oja.full.esm.js';

export default async function({ find, on, onUnmount, ready, inject }) {
    const { store, api, hcl: hclMod } = inject('app');
    const { highlightHCL, formatHCL, HCL_CSS } = hclMod;

    if (!document.getElementById('hcl-theme')) {
        const s = document.createElement('style'); s.id = 'hcl-theme'; s.textContent = HCL_CSS; document.head.appendChild(s);
    }

    let _prevConfig=null,_currConfig=null,_allHosts={},_rawFormat='json',_rawExpanded=false,_globalObj=null;

    const _hostsPg = pagination({ pageSize: 10, onPageChange: () => renderHostsSummary(_allHosts) });
    _hostsPg.mount(find('#configHostsPager'));

    const set = (id, v) => { const e = find('#' + id); if (e) e.innerText = v ?? '—'; };

    function formatBytes(b) { if(!b)return'0 B';const k=1024,s=['B','KB','MB','GB','TB'];const i=Math.floor(Math.log(b)/Math.log(k));return parseFloat((b/Math.pow(k,i)).toFixed(1))+' '+s[i]; }
    function fmtNum(n) { if(!n)return'0';if(n>=1000000)return(n/1000000).toFixed(1)+'M';if(n>=1000)return(n/1000).toFixed(1)+'k';return String(n); }
    function formatUptime(val) { if(!val)return'—';if(typeof val==='string')return val;const seconds=parseInt(val,10);if(isNaN(seconds))return String(val);const d=Math.floor(seconds/86400),h=Math.floor((seconds%86400)/3600),m=Math.floor((seconds%3600)/60);return[d>0&&`${d}d`,h>0&&`${h}h`,m>0&&`${m}m`].filter(Boolean).join(' ')||'<1m'; }
    function countBackends(host){let n=0;(host.routes||[]).forEach(r=>n+=r.backends?.servers?.length||0);(host.proxies||[]).forEach(p=>n+=p.backends?.length||0);return n;}
    function getRouteCount(hosts){let n=0;Object.values(hosts||{}).forEach(h=>{n+=(h.routes?.length||0)+(h.proxies?.length||0);});return n;}
    function getTLSCount(hosts){let n=0;Object.values(hosts||{}).forEach(h=>{if(h.tls?.mode&&h.tls.mode!=='none')n++;});return n;}

    function renderConfigMetrics(config,uptime){const g=config.global||{},sys=uptime?.system||{},hosts=config.hosts||{};set('configHttpPort',g.bind?.http?.[0]?.replace(':','')||'80');set('configHttpsPort',g.bind?.https?.[0]?.replace(':','')||'443');set('configVersion','v'+(g.version||'?'));set('configBuild',g.build||'dev');set('configLogLevel',(g.logging?.level||'info').toUpperCase());set('configHostCount',fmtNum(Object.keys(hosts).length));set('configRouteCount',fmtNum(getRouteCount(hosts)));set('configTlsCount',fmtNum(getTLSCount(hosts)));set('configNodeId',sys.node_id||g.node_id||'standalone');set('configHostname',sys.hostname||window.location.hostname);set('configPid',sys.pid||'—');set('configStartTime',sys.start_time?new Date(sys.start_time).toLocaleString():'—');const titleEl=find('#configPageTitle');if(titleEl)titleEl.innerHTML=`Configuration Overview <span style="font-size:14px;color:var(--text-mute);margin-left:10px;">v${g.version||'?'} (${g.build||'dev'})</span>`;}
    function renderGlobalSettings(g){const el=find('#configGlobalDetails');if(!el||!g)return;const trusted=g.security?.trusted_proxies||[];const settings=[{label:'Environment',value:g.development?'development':'production'},{label:'Admin Email',value:g.lets_encrypt?.email||'—'},{label:'Max Header Size',value:g.general?.max_header_bytes?formatBytes(g.general.max_header_bytes):'—'},{label:'Trusted Proxies',value:trusted.length>0?trusted.length+' configured':'none'},{label:'Read Timeout',value:g.timeouts?.read||'—'},{label:'Write Timeout',value:g.timeouts?.write||'—'},{label:'Idle Timeout',value:g.timeouts?.idle||'—'}];el.innerHTML=settings.map(s=>`<div class="config-detail-item"><div class="config-detail-label">${s.label}</div><div class="config-detail-value">${s.value}</div></div>`).join('');}
    function renderTlsSummary(certificates,config){const el=find('#configTlsSummary');if(!el)return;const total=certificates.length,valid=certificates.filter(c=>c.days_left>0).length,expiring=certificates.filter(c=>c.days_left>0&&c.days_left<7).length,expired=certificates.filter(c=>c.days_left!==null&&c.days_left<=0).length;el.innerHTML=[['Total Certificates',total],['Valid',`<span class="badge success">${valid}</span>`],['Expiring Soon',`<span class="badge warning">${expiring}</span>`],['Expired',`<span class="badge error">${expired}</span>`]].map(([l,v])=>`<div class="config-detail-item"><div class="config-detail-label">${l}</div><div class="config-detail-value">${v}</div></div>`).join('');const noteEl=find('#configTlsNote');if(noteEl&&config.global?.lets_encrypt){noteEl.innerHTML=`<span class="config-note-text">🔒 Auto-TLS: ${config.global.lets_encrypt.email||'No email'} | Staging: ${config.global.lets_encrypt.staging?'Yes':'No'}</span>`;}}
    function renderRuntimeSettings(uptime){const el=find('#configRuntimeDetails');if(!el||!uptime?.system)return;const sys=uptime.system;el.innerHTML=[['PID',sys.pid||'—'],['Uptime',formatUptime(sys.uptime)],['Start Time',sys.start_time?new Date(sys.start_time).toLocaleString():'—'],['Goroutines',sys.num_goroutine||0],['CPU Cores',sys.num_cpu||'—'],['Memory RSS',formatBytes(sys.mem_rss||0)],['Memory Alloc',formatBytes(sys.mem_alloc||0)]].map(([l,v])=>`<div class="config-detail-item"><div class="config-detail-label">${l}</div><div class="config-detail-value">${v}</div></div>`).join('');}
    function renderFeatureFlags(config){const el=find('#configFeatures');if(!el)return;const features=[];if(config.global?.development)features.push({name:'Development Mode',icon:'🔧'});if(config.global?.lets_encrypt?.enabled==='on')features.push({name:'Auto TLS',icon:'🔐'});if(config.cluster?.enabled)features.push({name:'Clustering',icon:'🌐'});if(config.global?.security?.trusted_proxies?.length)features.push({name:'Trusted Proxies',icon:'🛡️'});let hasWasm=false,hasRL=false,hasAuth=false,hasComp=false;Object.values(config.hosts||{}).forEach(host=>{(host.routes||[]).forEach(r=>{if(r.wasm?.enabled==='on')hasWasm=true;if(r.rate_limit?.enabled==='on')hasRL=true;if(r.basic_auth?.enabled==='on'||r.jwt_auth?.enabled==='on')hasAuth=true;if(r.compression?.enabled==='on')hasComp=true;});});if(hasWasm)features.push({name:'WASM Filters',icon:'⚡'});if(hasRL)features.push({name:'Rate Limiting',icon:'⏱️'});if(hasAuth)features.push({name:'Authentication',icon:'🔑'});if(hasComp)features.push({name:'Compression',icon:'🗜️'});if(!features.length){el.innerHTML='<div class="empty-state">No special features enabled</div>';return;}el.innerHTML=features.map(f=>`<div class="feature-item"><span class="feature-icon">${f.icon}</span><span class="feature-name">${f.name}</span><span class="feature-status success">✓</span></div>`).join('');}
    function renderHostsSummary(hosts){_allHosts=hosts||{};const tbody=find('#configHostsBody');if(!tbody)return;const entries=Object.entries(_allHosts);if(!entries.length){tbody.innerHTML='<tr><td colspan="5"><div class="empty-state">No hosts configured</div></td></tr>';_hostsPg.updateTotal(0);return;}_hostsPg.updateTotal(entries.length);const page=_hostsPg.slice(entries);tbody.innerHTML=page.map(([hostname,host])=>{const routeCount=(host.routes?.length||0)+(host.proxies?.length||0),backendCount=countBackends(host),tlsMode=host.tls?.mode||'none',tlsCls=tlsMode==='none'?'error':(tlsMode.includes('local')?'warning':'success'),tlsTxt=tlsMode==='none'?'No TLS':(tlsMode.includes('local')?'Local':'Auto'),domains=(host.domains||[]).slice(0,2).join(', ')+(host.domains?.length>2?'…':'');return`<tr><td class="mono">${hostname}</td><td>${routeCount}</td><td>${backendCount}</td><td><span class="badge ${tlsCls}">${tlsTxt}</span></td><td>${domains}</td></tr>`;}).join('');}
    function renderGitSection(gitStats){const section=find('#configGitSection'),details=find('#configGitDetails');if(!section||!details)return;const entries=Object.entries(gitStats||{});if(!entries.length){section.style.display='none';return;}section.style.display='';details.innerHTML=entries.map(([id,gs])=>{const cls=gs.state==='healthy'?'success':gs.state==='unavailable'?'warning':'error',commit=gs.commit?gs.commit.substring(0,8):'—';return`<div class="config-detail-item"><div class="config-detail-label">${id}</div><div class="config-detail-value"><span class="badge ${cls}">${gs.state||'unknown'}</span><span class="mono" style="font-size:10px;margin-left:4px;">${commit}</span><span style="color:var(--text-mute);font-size:10px;"> · ${gs.deployments||0} deploys</span></div></div>`;}).join('');}

    function _jsonToHCLHint(obj,indent=0){if(!obj||typeof obj!=='object')return String(obj??'');const pad='  '.repeat(indent),lines=[];for(const[k,v]of Object.entries(obj)){if(v===null||v===undefined)continue;const key=k.replace(/-/g,'_');if(typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length>0){lines.push(`${pad}${key} {`);lines.push(_jsonToHCLHint(v,indent+1));lines.push(`${pad}}`);}else if(Array.isArray(v)){const vals=v.map(x=>typeof x==='string'?`"${x}"`:String(x));lines.push(`${pad}${key} = [${vals.join(', ')}]`);}else if(typeof v==='string'){lines.push(`${pad}${key} = "${v}"`);}else{lines.push(`${pad}${key} = ${v}`);}}return lines.join('\n');}
    function _refreshRaw(){const el=find('#configContent');if(!el||!_globalObj)return;if(_rawFormat==='hcl'){el.innerHTML=highlightHCL(_jsonToHCLHint(_globalObj));}else{const json=JSON.stringify(_globalObj,null,2);el.innerHTML=json.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}}
    function renderRawConfig(config){_globalObj=config?.global||config;_refreshRaw();}
    function renderAll(config,uptime){if(!config||config.__offline)return;_prevConfig=_currConfig;_currConfig=config;renderConfigMetrics(config,uptime);renderGlobalSettings(config.global);renderTlsSummary(store.get('certificates')||[],config);renderRuntimeSettings(uptime);renderFeatureFlags(config);renderHostsSummary(config.hosts);renderGitSection(uptime?.git||store.get('gitStats')||{});renderRawConfig(config);}

    async function refresh(){const btn=find('#configRefreshBtn');ui.btn.loading(btn,'⟳ Loading…');const[config,uptime]=await Promise.all([api.fetchConfig(),api.fetchUptime()]);ui.btn.reset(btn);if(config&&!config.__offline&&!config.__unauthorized){store.set('lastConfig',config);store.set('lastUptime',uptime);if(uptime?.git)store.set('gitStats',uptime.git);}renderAll(config,uptime);}

    const cachedConfig=store.get('lastConfig'),cachedUptime=store.get('lastUptime');
    if(cachedConfig)renderAll(cachedConfig,cachedUptime); else refresh();

    on('#configRefreshBtn','click',refresh);

    tabs.render(find('#configFormatTabs'),[{key:'json',label:'JSON'},{key:'hcl',label:'HCL'}],{active:'json',variant:'pill',onChange:(key)=>{_rawFormat=key;_refreshRaw();}});

    on('#configCopyBtn','click',()=>{const text=find('#configContent')?.innerText||'';clipboard.write(text).then(()=>notify.show('Copied','success')).catch(()=>notify.show('Copy failed','error'));});
    on('#configExpandBtn','click',(e,btn)=>{const box=find('#configContent');if(!box)return;_rawExpanded=!_rawExpanded;box.style.maxHeight=_rawExpanded?'none':'360px';if(btn)btn.textContent=_rawExpanded?'↕️ Collapse':'↕️ Expand';});
    on('#configDiffBtn','click',()=>{const section=find('#configDiffSection'),diffEl=find('#configDiff');if(!section||!diffEl)return;if(section.style.display!=='none'){section.style.display='none';return;}if(!_prevConfig||!_currConfig){diffEl.textContent='Refresh once more to compare with previous version.';}else{const oldStr=JSON.stringify(_prevConfig,null,2).split('\n'),newStr=JSON.stringify(_currConfig,null,2).split('\n');if(oldStr.join('')===newStr.join('')){diffEl.textContent='No changes detected.';}else{let out='';for(let i=0;i<Math.max(oldStr.length,newStr.length);i++){if(oldStr[i]!==newStr[i]){if(oldStr[i])out+=`- ${oldStr[i]}\n`;if(newStr[i])out+=`+ ${newStr[i]}\n`;}else{out+=`  ${oldStr[i]}\n`;}}diffEl.textContent=out;}}section.style.display='';});

    ready();
}
